### ISSUE TITLE
Spain's language code should be "es" and not "spa"

### ISSUE THREAD

**Issue by leamarty** [Vic-rider/countries-speaking-languages#13]
Hi there! First of all, thank you for this library! I couldn't find any other better than this one!

One super small thing I came across while using it is that Spain's Spanish code is wrong.
The 3 occurrences say:
```
{ "language": "Spanish", "code": "spa" },
```

But the actual code for Spanish is "es". So it should be:
```
{ "language": "Spanish", "code": "es" },
```

Every single other country that speaks Spanish (like most Latin-American countries, Argentina, Mexico, Chile, Colombia...) are actually correct... they all say "es". Only Spain is wrong.

Thanks again for this great lib!

**Comment by Vic-rider** [comment]
Hi @leamarty. Thank you. It's a pleasure to feel useful to you.

**Comment by Vic-rider** [comment]
I hope we can close this.
